name: bbml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib_metadata=7.0.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.5
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - traitlets=5.14.0
  - typing_extensions=4.9.0
  - wcwidth=0.2.12
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==3.7.1
      - attrs==23.1.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - distlib==0.3.7
      - fastapi==0.105.0
      - filelock==3.13.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - greenlet==3.0.2
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.2
      - identify==2.5.33
      - idna==3.6
      - importlib-metadata==6.11.0
      - iniconfig==2.0.0
      - jinja2==3.1.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mysql-connector-python==8.2.0
      - nodeenv==1.8.0
      - numpy==1.26.2
      - pandas==2.1.4
      - pillow==10.1.0
      - pluggy==1.3.0
      - pre-commit==3.6.0
      - protobuf==4.21.12
      - pyarrow==14.0.1
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pydeck==0.8.1b0
      - pytest==7.4.3
      - python-dotenv==1.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.32.0
      - requests==2.31.0
      - rich==13.7.0
      - rootutils==1.0.7
      - rpds-py==0.13.2
      - smmap==5.0.1
      - sniffio==1.3.0
      - sqlalchemy==2.0.23
      - starlette==0.27.0
      - streamlit==1.29.0
      - tenacity==8.2.3
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.4
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - validators==0.22.0
      - virtualenv==20.25.0
      - watchdog==3.0.0
